
            <?php foreach ($this->menu as $menu): ?>
              <li>
                 <a href="<?php 
                 echo $this->url(array(
                     'controller' => $menu['controller'],
                     'action'=>$menu['action'])
                         ,  'default' 
                         )?>">
                             <?php echo $menu['tytul'] ?></a></li>
              <?php endforeach;?>
          


 

