<!DOCTYPE html>
        <html>
        <head>
	<?php 
        echo $this->headMeta(); 
    // echo $this->JQuery();
        ?>
        <link href="<?php echo $this->baseUrl('css/bootstrap.css') ?>" rel="stylesheet" media="screen">
        <link href="<?php echo $this->baseUrl('js/bootstrap.js') ?>" rel="stylesheet" media="screen">

        <title>BOK</title>
        
        </head>
        <body>
             <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                   
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>
                   <?php echo $this->menu(); ?>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
             </nav>
<?php echo $this->layout()->content; ?>

                 
                 
                                  
                 

</body>
</html>