<!DOCTYPE html>
        <html>
        <head>
	<?php 
        echo $this->headMeta(); 
    echo $this->JQuery();
        ?>
        <link href="<?php echo $this->baseUrl('css/bootstrap.css') ?>" rel="stylesheet" media="screen">
        <link href="<?php echo $this->baseUrl('css/bootstrap-theme.css') ?>" rel="stylesheet" media="screen">
        <script type="text/javascript" src="<?php echo $this->baseUrl('js/bootstrap.min.js')?>"> </script>
       
        <title>BOK</title>
        
        </head>
        <body>
            <nav class="navbar navbar-inverse" role="navigation">
            <div class="container-fluid">
              <div class="collapse navbar-collapse">
                   <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                       <ul class="nav navbar-nav">
                           
                           <li class="dropdown">
                             <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                               <ul class="dropdown-menu" role="menu">
                               <?php echo $this->menu(); ?>     
                               </ul>
                           </li>
                           
                       </ul>
                   </div>
                    
                  
                </div>
                
                
                
                
                
            
            
            
            </nav>
        
         
<?php echo $this->layout()->content; ?>

                 
                 
                                  
                 
 
</body>
</html>